const translations={
en:{newOcr:"New OCR",history:"History",settings:"Settings",workspace:"WORKSPACE",newOcrSubtitle:"Convert PDF files into Markdown.",localNote:"Runs locally on this computer.",sourceTitle:"Choose your PDF sources",sourceHint:"Paste one file or folder path per line, or use the buttons below.",sources:"PDF FILES OR FOLDERS",chooseFiles:"Choose files",chooseFolder:"Choose folder",destination:"DESTINATION",outputFolder:"Output folder",browse:"Browse",sameFolder:"Save each Markdown file beside its PDF",reprocess:"Reprocess existing Markdown",scanAndStart:"Scan and start OCR",currentRun:"CURRENT RUN",pause:"Pause",resume:"Resume",pauseWorking:"Pausing…",cancel:"Cancel",cancelWorking:"Cancelling…",openLocation:"Open location",archive:"ARCHIVE",historyTitle:"Processing history",historySubtitle:"Review completed and interrupted OCR operations.",runs:"Runs",files:"Files",pages:"Pages",general:"General",apiKeys:"API keys",preferences:"PREFERENCES",generalSettings:"General settings",language:"Language",defaultOutput:"Default output folder",save:"Save settings",credentials:"CREDENTIALS",keysHint:"Name each key and record when its credits or subscription renew.",import:"Import",addKey:"Add API key",provider:"Provider",name:"Name",email:"Account email (optional)",apiKey:"API key",renewalDate:"Credits/subscription renewal date",enabled:"Enabled",cancel:"Cancel",edit:"Edit",test:"Test",delete:"Delete",noKeys:"No API keys configured.",processing:"Processing",completed:"Completed",failed:"Failed",skipped:"Skipped",pending:"Pending",cancelled:"Cancelled",created:"Created",completed_with_errors:"Completed with errors",noRuns:"No runs yet.",scanFound:"Found",saved:"Saved",imported:"Imported",confirmDelete:"Delete this API key?",connectionSucceeded:"Connection succeeded",credits_exhausted:"Credits exhausted",unavailable:"Unavailable",renewal:"Renews"},
ar:{newOcr:"OCR جديد",history:"السجل",settings:"الإعدادات",workspace:"مساحة العمل",newOcrSubtitle:"حوّل ملفات PDF إلى Markdown.",localNote:"يعمل محلياً على هذا الكمبيوتر.",sourceTitle:"اختر مصادر ملفات PDF",sourceHint:"ألصق مسار ملف أو مجلد في كل سطر، أو استخدم الأزرار بالأسفل.",sources:"ملفات أو مجلدات PDF",chooseFiles:"اختيار ملفات",chooseFolder:"اختيار مجلد",destination:"المخرجات",outputFolder:"مجلد المخرجات",browse:"استعراض",sameFolder:"حفظ كل ملف Markdown بجوار ملف PDF",reprocess:"إعادة معالجة ملفات Markdown الموجودة",scanAndStart:"فحص وبدء OCR",currentRun:"التشغيل الحالي",pause:"إيقاف مؤقت",resume:"متابعة",pauseWorking:"جارٍ الإيقاف المؤقت…",cancel:"إلغاء",cancelWorking:"جارٍ الإلغاء…",openLocation:"فتح مكان الملف",archive:"الأرشيف",historyTitle:"سجل المعالجة",historySubtitle:"راجع عمليات OCR المكتملة والمتوقفة.",runs:"تشغيلات",files:"ملفات",pages:"صفحات",general:"عام",apiKeys:"مفاتيح API",preferences:"التفضيلات",generalSettings:"الإعدادات العامة",language:"اللغة",defaultOutput:"مجلد المخرجات الافتراضي",save:"حفظ الإعدادات",credentials:"بيانات الاعتماد",keysHint:"سمِّ كل مفتاح وسجّل موعد تجدد الرصيد أو الاشتراك.",import:"استيراد",addKey:"إضافة مفتاح API",provider:"المزوّد",name:"الاسم",email:"البريد الإلكتروني للحساب (اختياري)",apiKey:"مفتاح API",renewalDate:"موعد تجدد الرصيد أو الاشتراك",enabled:"مفعّل",cancel:"إلغاء",edit:"تعديل",test:"اختبار",delete:"حذف",noKeys:"لم تتم إضافة مفاتيح API.",processing:"قيد المعالجة",completed:"مكتمل",failed:"فشل",skipped:"تم تخطيه",pending:"قيد الانتظار",cancelled:"ملغى",created:"مُنشأ",completed_with_errors:"اكتمل مع أخطاء",noRuns:"لا توجد تشغيلات بعد.",scanFound:"تم العثور على",saved:"تم الحفظ",imported:"تم الاستيراد",confirmDelete:"حذف مفتاح API هذا؟",connectionSucceeded:"نجح الاتصال",credits_exhausted:"الرصيد مستنفد",unavailable:"غير متاح",renewal:"التجدد"}
};
let lang="en",state=null,currentRunId=null,pollTimer=null,editingId=null;
const $=id=>document.getElementById(id),t=k=>(translations[lang]?.[k]||translations.en[k]||k),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bridge=()=>window.pywebview.api;
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2800)}
function translate(){document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";$("pageTitle").textContent=t(document.querySelector(".nav-item.active")?.dataset.page==="new"?"newOcr":document.querySelector(".nav-item.active")?.dataset.page||"newOcr")}
function showPage(name){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===`page-${name}`));document.querySelectorAll(".nav-item").forEach(p=>p.classList.toggle("active",p.dataset.page===name));$("pageTitle").textContent=t(name==="new"?"newOcr":name);$("pageSubtitle").textContent=name==="new"?t("newOcrSubtitle"):name==="history"?t("historySubtitle"):t("keysHint");if(name==="history")renderHistory()}
function renderState(){if(!state)return;lang=state.settings.language||"en";translate();$("outputDir").value=state.settings.default_output||"";$("settingsOutput").value=state.settings.default_output||"";$("settingsLanguage").value=lang;renderHistory();renderCredentials()}
function renderHistory(){const runs=state?.runs||[];let files=0,pages=0;runs.forEach(r=>{files+=r.total||0;pages+=r.pages||0});$("statRuns").textContent=runs.length;$("statFiles").textContent=files;$("statPages").textContent=pages;const el=$("historyList");if(!runs.length){el.innerHTML=`<div class="message">${t("noRuns")}</div>`;return}el.innerHTML=runs.map(r=>`<div class="history-row"><div><strong>${esc(r.output_mode==="same_folder"?t("sameFolder"):r.output_dir)}</strong><small>${esc(r.created_at)} · ${r.total||0} ${t("files")} · ${r.pages||0} ${t("pages")}</small></div><span class="status ${esc(r.status)}">${esc(t(r.status)||r.status)}</span><button class="button quiet" onclick="openRun('${r.id}')">${t("history")}</button></div>`).join("")}
function renderCredentials(){const el=$("credentialList"),items=state?.credentials||[];if(!items.length){el.innerHTML=`<div class="message">${t("noKeys")}</div>`;return}el.innerHTML=items.map(c=>{const status=c.status||"ready";return `<div class="credential-row"><div><strong>${esc(c.name)} <span class="status">${esc(c.masked)}</span></strong><small>${esc(c.email||"—")} · ${esc(c.provider)} · ${t("renewal")}: ${esc(c.renewal_date||"—")}</small></div><span class="status ${status}">${esc(t(status)||status)}</span><div class="credential-actions"><button class="button quiet" onclick="testCredential('${c.id}')">${t("test")}</button><button class="button quiet" onclick="editCredential('${c.id}')">${t("edit")}</button><button class="button quiet" onclick="deleteCredential('${c.id}')">${t("delete")}</button></div></div>`}).join("")}
async function refresh(){try{state=await bridge().state();renderState()}catch(e){toast(e.message||String(e))}}
async function choose(kind,target){try{const paths=await bridge()[kind]();if(paths?.length){const old=$(target).value.trim();$(target).value=[old,...paths].filter(Boolean).join("\n")}}catch(e){toast(e.message||String(e))}}
async function scan(){try{const result=await bridge().validate_paths($("inputPaths").value,$("outputDir").value,$("sameFolder").checked),el=$("pathValidation");el.className=`message ${result.warnings.length?"error":"success"}`;el.textContent=`${t("scanFound")} ${result.count} ${t("files")}.`+(result.warnings.length?"\n"+result.warnings.join("\n"):"");return result}catch(e){$("pathValidation").className="message error";$("pathValidation").textContent=e.message||String(e);throw e}}
async function start(){try{const check=await scan();if(!check.count)return;const run=await bridge().create_run($("inputPaths").value,$("outputDir").value,$("sameFolder").checked,$("forceExisting").checked);currentRunId=run.run.id;await bridge().start_run(currentRunId);$("monitorPanel").classList.remove("hidden");poll();toast(t("processing"))}catch(e){toast(e.message||String(e))}}
async function poll(){if(!currentRunId)return;try{const detail=await bridge().get_run(currentRunId),r=detail.run,c=r.counts||{};$("runTitle").textContent=esc(r.output_dir);$("runSummary").textContent=`${esc(r.message||r.status)} · ${c.completed||0}/${r.total||0} ${t("completed")} · ${c.failed||0} ${t("failed")}`;$("pauseRun").textContent=r.status==="paused"?t("resume"):t("pause");$("documentList").innerHTML=detail.documents.map(d=>`<div class="document-row"><div>${esc(d.source_path)}<small>${esc(d.error||d.output_path)}</small></div><span class="status ${esc(d.status)}">${esc(t(d.status)||d.status)}</span></div>`).join("");if(["completed","completed_with_errors","cancelled","failed"].includes(r.status)){clearTimeout(pollTimer);await refresh();return}pollTimer=setTimeout(poll,1200)}catch(e){toast(e.message||String(e))}}
async function revealOutput(encodedPath){try{await bridge().reveal_path(decodeURIComponent(encodedPath))}catch(e){toast(e.message||String(e))}}
function openRun(id){currentRunId=id;showPage("new");$("monitorPanel").classList.remove("hidden");poll()}
function openModal(id=null){editingId=id;const c=state.credentials.find(x=>x.id===id);$("credentialDialogTitle").textContent=id?t("edit"):t("addKey");$("credentialProvider").value=c?.provider||"mistral";$("credentialName").value=c?.name||"";$("credentialEmail").value=c?.email||"";$("credentialSecret").value="";$("credentialSecret").required=!id;$("credentialRenewal").value=c?.renewal_date||"";$("credentialEnabled").checked=c?.enabled??true;$("credentialModal").classList.remove("hidden")}
function closeModal(){$("credentialModal").classList.add("hidden")}
async function saveCredential(e){e.preventDefault();try{const values={provider:$("credentialProvider").value,name:$("credentialName").value,email:$("credentialEmail").value,secret:$("credentialSecret").value,renewal:$("credentialRenewal").value,enabled:$("credentialEnabled").checked};if(editingId)await bridge().update_credential(editingId,values.name,values.email,values.enabled,values.renewal,values.secret);else await bridge().add_credential(values.provider,values.name,values.email,values.secret,values.renewal);closeModal();await refresh();toast(t("saved"))}catch(e){toast(e.message||String(e))}}
function editCredential(id){openModal(id)}
async function deleteCredential(id){if(!confirm(t("confirmDelete")))return;try{await bridge().delete_credential(id);await refresh()}catch(e){toast(e.message||String(e))}}
async function testCredential(id){try{const result=await bridge().test_credential(id);toast(result.message);await refresh()}catch(e){toast(e.message||String(e))}}
async function importCredentials(){try{const files=await bridge().pick_json();if(!files?.length)return;const result=await bridge().import_credentials(files[0]);toast(`${t("imported")}: ${result.imported}`);await refresh()}catch(e){toast(e.message||String(e))}}
async function saveSettings(){try{const result=await bridge().save_settings({language:$("settingsLanguage").value,default_output:$("settingsOutput").value});state.settings=result;lang=result.language;translate();$("outputDir").value=result.default_output;toast(t("saved"))}catch(e){toast(e.message||String(e))}}
async function openOutputFolder(){try{const detail=await bridge().get_run(currentRunId);await bridge().reveal_path(detail.run.output_dir)}catch(e){toast(e.message||String(e))}}
window.openRun=openRun;window.revealOutput=revealOutput;window.openOutputFolder=openOutputFolder;window.editCredential=editCredential;window.deleteCredential=deleteCredential;window.testCredential=testCredential;
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));document.querySelectorAll(".settings-tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".settings-tab,.settings-section").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("settings-"+b.dataset.settingsTab).classList.add("active")}));$("browseFiles").addEventListener("click",()=>choose("pick_files","inputPaths"));$("browseFolder").addEventListener("click",()=>choose("pick_folder","inputPaths"));$("browseOutput").addEventListener("click",async()=>{const p=await bridge().pick_folder();if(p?.[0])$("outputDir").value=p[0]});$("browseSettingsOutput").addEventListener("click",async()=>{const p=await bridge().pick_folder();if(p?.[0])$("settingsOutput").value=p[0]});$("sameFolder").addEventListener("change",()=>{$("outputDir").disabled=$("sameFolder").checked;$("browseOutput").disabled=$("sameFolder").checked});$("scanAndStart").addEventListener("click",start);$("pauseRun").addEventListener("click",async()=>{const d=await bridge().get_run(currentRunId);if(d.run.status==="paused")await bridge().resume_run(currentRunId);else await bridge().pause_run(currentRunId);poll()});$("cancelRun").addEventListener("click",async()=>{await bridge().cancel_run(currentRunId);poll()});$("addCredential").addEventListener("click",()=>openModal());$("closeCredential").addEventListener("click",closeModal);$("cancelCredential").addEventListener("click",closeModal);$("credentialForm").addEventListener("submit",saveCredential);$("importCredentials").addEventListener("click",importCredentials);$("saveSettings").addEventListener("click",saveSettings);$("settingsLanguage").addEventListener("change",()=>{lang=$("settingsLanguage").value;translate()})});window.addEventListener("pywebviewready",refresh);
